app:
  instanceId: TEST1
spring:
    datasource:
      url: jdbc:mariadb://localhost:3320/register
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
    profile: dev
jwt:
    secret: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
    expiration: 3600000

logging:
  level:
    root: INFO